/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//rad194 ska läggas in db ändringar.

package ngo2024.fonster;

import ngo2024.Anvandare;
import ngo2024.Validerare;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.ImageIcon;

/**
 *
 * @author Gastinlogg
 */
public class AndraLosenordFonster extends javax.swing.JFrame {

    private InfDB idb;
    private Anvandare inloggadAnvandare;
    private MinaUppgifterFonster minaUppgifterFonster;
    /**
     * Creates new form AndraLosenord
     */
    public AndraLosenordFonster(InfDB idb, Anvandare inloggadAnvandare, MinaUppgifterFonster minaUppgifterFonster) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.minaUppgifterFonster = minaUppgifterFonster;
        setLocationRelativeTo(null);
        lblFelmeddelandeNyttLosenord.setVisible(false);
        lblFelmeddelandeOrginalLosenord.setVisible(false);
    }
    
    private void updateDB(String nyttLosenord){
        String sqlFraga = "UPDATE anstalld SET "
                + "losenord = '" + nyttLosenord + "' "
                + "WHERE aid = " + inloggadAnvandare.getAnstallningsID();
        try{
            idb.update(sqlFraga);
            inloggadAnvandare = new Anvandare(idb, inloggadAnvandare.getAnstallningsID());
        }
        catch(InfException ex){
            System.out.println(ex.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTidigareLosenord = new javax.swing.JLabel();
        lblNyttLosenord = new javax.swing.JLabel();
        lblUpprepaLosenord = new javax.swing.JLabel();
        tfTidigareLosenord = new javax.swing.JTextField();
        tfNyttLosenord = new javax.swing.JTextField();
        tfUpprepaLosenord = new javax.swing.JTextField();
        btnSparaNyttLosenord = new javax.swing.JButton();
        btnAvbryt = new javax.swing.JButton();
        lblFelmeddelandeNyttLosenord = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFelmeddelandeOrginalLosenord = new javax.swing.JLabel();

        setTitle("SDG Sweden - Ändra lösenord");
        setIconImage(new ImageIcon(getClass().getResource("/resources/icons/appLogo.png")).getImage());
        setResizable(false);

        lblTidigareLosenord.setText("Tidigare lösenord:");

        lblNyttLosenord.setText("Nytt lösenord:");

        lblUpprepaLosenord.setText("Upprepa nytt lösenord:");

        tfTidigareLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTidigareLosenordActionPerformed(evt);
            }
        });

        tfNyttLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNyttLosenordActionPerformed(evt);
            }
        });

        btnSparaNyttLosenord.setText("Spara nytt lösenord");
        btnSparaNyttLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaNyttLosenordActionPerformed(evt);
            }
        });

        btnAvbryt.setText("Avbryt");
        btnAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvbrytActionPerformed(evt);
            }
        });

        lblFelmeddelandeNyttLosenord.setForeground(new java.awt.Color(255, 0, 51));
        lblFelmeddelandeNyttLosenord.setText("Lösenordet matchar inte!");

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));

        lblFelmeddelandeOrginalLosenord.setForeground(new java.awt.Color(255, 0, 51));
        lblFelmeddelandeOrginalLosenord.setText("Angivet lösenord är felaktigt!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTidigareLosenord)
                                    .addComponent(lblNyttLosenord)
                                    .addComponent(lblUpprepaLosenord))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfTidigareLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(tfNyttLosenord)
                                    .addComponent(tfUpprepaLosenord)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblFelmeddelandeOrginalLosenord))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFelmeddelandeNyttLosenord)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAvbryt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(btnSparaNyttLosenord)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTidigareLosenord)
                    .addComponent(tfTidigareLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(lblFelmeddelandeOrginalLosenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNyttLosenord)
                    .addComponent(tfNyttLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpprepaLosenord)
                    .addComponent(tfUpprepaLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblFelmeddelandeNyttLosenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvbryt)
                    .addComponent(btnSparaNyttLosenord))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNyttLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNyttLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNyttLosenordActionPerformed

    private void tfTidigareLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTidigareLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTidigareLosenordActionPerformed

    private void btnAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvbrytActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnAvbrytActionPerformed

    private void btnSparaNyttLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaNyttLosenordActionPerformed
        lblFelmeddelandeOrginalLosenord.setVisible(false);
        lblFelmeddelandeNyttLosenord.setVisible(false);
        String losenord = inloggadAnvandare.getLosenord();
        String angivetLosenord = tfTidigareLosenord.getText();
        if(losenord.equals(angivetLosenord)){
            String nyttLosenord1 = tfNyttLosenord.getText();
            String nyttLosenord2 = tfUpprepaLosenord.getText();
            if(!nyttLosenord1.isEmpty() && !nyttLosenord2.isEmpty()){ 
                if(nyttLosenord1.equals(nyttLosenord2)){
                   if(Validerare.formatLosenord(nyttLosenord1)){
                       //ska ändra i db 
                       updateDB(nyttLosenord1);
                       System.out.println("Korrekt");
                       this.setVisible(false);
                       minaUppgifterFonster.setVisible(false);
                       new MinaUppgifterFonster(idb,inloggadAnvandare).setVisible(true);
                       
                    }
                   else {
                        String felMed = "Lösenordet måste innehålla 8 tecken och minst 1 siffra.";
                        lblFelmeddelandeNyttLosenord.setText(felMed);
                        lblFelmeddelandeNyttLosenord.setVisible(true);
                   }
                }
                else{
                    lblFelmeddelandeNyttLosenord.setText("Lösenordet matchar inte!");
                    lblFelmeddelandeNyttLosenord.setVisible(true);
                }
            }
            else{
                lblFelmeddelandeNyttLosenord.setText("Fyll i alla fält!");
                lblFelmeddelandeNyttLosenord.setVisible(true);
            }
        }
        else {
            lblFelmeddelandeOrginalLosenord.setVisible(true);
        }
    }//GEN-LAST:event_btnSparaNyttLosenordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraLosenordFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraLosenordFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraLosenordFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraLosenordFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AndraLosenord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvbryt;
    private javax.swing.JButton btnSparaNyttLosenord;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFelmeddelandeNyttLosenord;
    private javax.swing.JLabel lblFelmeddelandeOrginalLosenord;
    private javax.swing.JLabel lblNyttLosenord;
    private javax.swing.JLabel lblTidigareLosenord;
    private javax.swing.JLabel lblUpprepaLosenord;
    private javax.swing.JTextField tfNyttLosenord;
    private javax.swing.JTextField tfTidigareLosenord;
    private javax.swing.JTextField tfUpprepaLosenord;
    // End of variables declaration//GEN-END:variables
}
