/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024.fonster;

import java.awt.Dimension;
import java.awt.Toolkit;
import oru.inf.InfDB;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import ngo2024.Anvandare;
import ngo2024.Projekt;
import oru.inf.InfException;

/**
 *
 * @author Gastinlogg
 */
public class HanteraAnstalldaFonster extends javax.swing.JFrame {

    private InfDB idb;
    private Anvandare inloggadAnvandare;

    /**
     * Creates new form HanteraAnstallda
     */
    public HanteraAnstalldaFonster(InfDB idb, Anvandare inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        setLocationRelativeTo(null);
        displayAnstallda();
        tblAnstallda.setDefaultEditor(Object.class, null);
        setWindowSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnstallda = new javax.swing.JTable();
        btnLaggTillAnstalld = new javax.swing.JButton();
        btnTaBortAnstalld = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SDG Sweden - Anställda");
        setMaximumSize(new java.awt.Dimension(1020, 576));

        tblAnstallda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AnställningsID", "Namn", "Roll", "Avdelning"
            }
        ));
        tblAnstallda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAnstalldaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAnstallda);

        btnLaggTillAnstalld.setText("Registrera anställd");
        btnLaggTillAnstalld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillAnstalldActionPerformed(evt);
            }
        });

        btnTaBortAnstalld.setText("Ta bort anställd");
        btnTaBortAnstalld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortAnstalldActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        jLabel1.setText("Klicka på den anställda som du vill ta bort!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTillbaka)
                        .addGap(18, 18, 18)
                        .addComponent(btnLaggTillAnstalld)
                        .addGap(18, 18, 18)
                        .addComponent(btnTaBortAnstalld)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGap(49, 235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnLaggTillAnstalld)
                    .addComponent(btnTaBortAnstalld)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setWindowSize(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int windowWidth = (int) (screenSize.width * 0.75);
        int windowHeight = (int) (screenSize.height * 0.75);
        int x = (screenSize.width - windowWidth) / 2;
        int y = (screenSize.height - windowHeight) / 2;
        setBounds(x, y, windowWidth, windowHeight);
        setLocationRelativeTo(null);
    }
    
    private void btnLaggTillAnstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillAnstalldActionPerformed
        new RegistreraAnstalldFonster(idb, inloggadAnvandare, this).setVisible(true);
    }//GEN-LAST:event_btnLaggTillAnstalldActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new MenyFonster(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed


    private void btnTaBortAnstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortAnstalldActionPerformed
        
        
    }//GEN-LAST:event_btnTaBortAnstalldActionPerformed

    private void tblAnstalldaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAnstalldaMouseClicked
        // Hämta raden som är vald när musen klickar
        int rad = tblAnstallda.rowAtPoint(evt.getPoint());
    
        // Om rad är vald (inte -1) och är inom tabellens intervall
        if (rad >= 0 && rad < tblAnstallda.getRowCount()) {
      
        // Hämta värdet från den första kolumnen (aid)
        String aid = tblAnstallda.getValueAt(rad, 0).toString();
        
        Anvandare anvandareAttTaBort = new Anvandare(idb, aid);

        // Skapa och öppna ett nytt fönster som skickar med aid
        new VarningJaNejFonster(anvandareAttTaBort, this).setVisible(true);
        }
    }//GEN-LAST:event_tblAnstalldaMouseClicked


    public void displayAnstallda() {
        try {

            String sqlFraga = "SELECT aid FROM anstalld ORDER BY aid ASC";

            ArrayList<String> anstallda = idb.fetchColumn(sqlFraga);

            sqlFraga = "SELECT aid FROM handlaggare ";
            ArrayList<String> handlaggare = idb.fetchColumn(sqlFraga);

            for (String aid : anstallda) {

                sqlFraga = "SELECT fornamn, efternamn, namn FROM anstalld "
                        + "JOIN avdelning ON anstalld.avdelning = avdelning.avdid "
                        + "WHERE aid =" + aid;

                HashMap<String, String> uppgifter = idb.fetchRow(sqlFraga);

                String namn = uppgifter.get("fornamn") + " " + uppgifter.get("efternamn");

                if (handlaggare.contains(aid)) {
                    DefaultTableModel model = (DefaultTableModel) tblAnstallda.getModel();

                    model.addRow(new Object[]{aid, namn, "Handläggare", uppgifter.get("namn")});
                } else {
                    DefaultTableModel model = (DefaultTableModel) tblAnstallda.getModel();

                    model.addRow(new Object[]{aid, namn, "Administratör", uppgifter.get("namn")});
                }

            }
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HanteraAnstalldaFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HanteraAnstalldaFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HanteraAnstalldaFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HanteraAnstalldaFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new HanteraAnstallda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTillAnstalld;
    private javax.swing.JButton btnTaBortAnstalld;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAnstallda;
    // End of variables declaration//GEN-END:variables
}
