/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024.fonster;

import ngo2024.*;
import oru.inf.InfDB;
import javax.swing.ImageIcon;

/**
 *
 * @author annae
 */
public class RedigeraLandFonster extends javax.swing.JFrame {

    private Anvandare inloggadAnvandare;
    private Land aktuelltLand;
    private InfDB idb;
    private LandFonster forraFonstret;
    
    private String originalNamn;
    private String originalSprak;
    private String originalValuta;
    private String originalTidszon;
    private String originalPolitiskStruktur;
    private String originalEkonomi;
    
    /**
     * Creates new form LandInfoFonster
     */
    public RedigeraLandFonster(Anvandare inloggadAnvandare, Land aktuelltLand, InfDB idb, LandFonster forraFonstret) {
        this.inloggadAnvandare = inloggadAnvandare;
        this.aktuelltLand = aktuelltLand;
        this.idb = idb;
        this.forraFonstret = forraFonstret;
        
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("SDG Sweden - Redigera " + aktuelltLand.getNamn());
        doljFelMeddelanden();
        setLandInfoText();
        btnSpara.setEnabled(false);
    }
    
    private void doljFelMeddelanden(){
        lblFelMNamn.setVisible(false);
        lblFelMSprak.setVisible(false);
        lblFelMValuta.setVisible(false);
        lblFelMTidszon.setVisible(false);
        lblFelMPolitiskStruktur.setVisible(false);
        lblFelMEkonomi.setVisible(false);
    }
    
    private void setLandInfoText(){
        originalNamn = aktuelltLand.getNamn();
        originalSprak = aktuelltLand.getSprak();
        originalValuta = aktuelltLand.getValuta();
        originalTidszon = aktuelltLand.getTidszon();
        originalPolitiskStruktur = aktuelltLand.getPolitiskStruktur();
        originalEkonomi = aktuelltLand.getEkonomi();
        
        tfNamn.setText(originalNamn);
        tfSprak.setText(originalSprak);
        tfValuta.setText(originalValuta);
        tfTidszon.setText(originalTidszon);
        tfPolitiskStruktur.setText(originalPolitiskStruktur);
        tfEkonomi.setText(originalEkonomi);
    }
    
    private boolean harOsparadeAndringar(){
        if(!originalNamn.equals(tfNamn.getText())){
            return true;
        }
        if(!originalSprak.equals(tfSprak.getText())){
            return true;
        }
        if(!originalValuta.equals(tfValuta.getText())){
            return true;
        }
        if(!originalTidszon.equals(tfTidszon.getText())){
            return true;
        }
        if(!originalPolitiskStruktur.equals(tfPolitiskStruktur.getText())){
            return true;
        }
        if(!originalEkonomi.equals(tfEkonomi.getText())){
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTillbaka = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        lblNamn = new javax.swing.JLabel();
        lblSprak = new javax.swing.JLabel();
        lblValuta = new javax.swing.JLabel();
        lblTidszon = new javax.swing.JLabel();
        lblEkonomi = new javax.swing.JLabel();
        lblPolitiskStruktur = new javax.swing.JLabel();
        tfNamn = new javax.swing.JTextField();
        tfSprak = new javax.swing.JTextField();
        tfValuta = new javax.swing.JTextField();
        tfTidszon = new javax.swing.JTextField();
        tfEkonomi = new javax.swing.JTextField();
        tfPolitiskStruktur = new javax.swing.JTextField();
        lblFelMSprak = new javax.swing.JLabel();
        lblFelMNamn = new javax.swing.JLabel();
        lblFelMValuta = new javax.swing.JLabel();
        lblFelMTidszon = new javax.swing.JLabel();
        lblFelMPolitiskStruktur = new javax.swing.JLabel();
        lblFelMEkonomi = new javax.swing.JLabel();

        setIconImage(new ImageIcon(getClass().getResource("/resources/icons/appLogo.png")).getImage());
        setResizable(false);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnSpara.setText("Spara uppgifter");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        lblNamn.setText("Namn:");

        lblSprak.setText("Språk:");

        lblValuta.setText("Valuta:");

        lblTidszon.setText("Tidszon:");

        lblEkonomi.setText("Ekonomi:");

        lblPolitiskStruktur.setText("Politisk struktur:");

        tfNamn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNamnKeyTyped(evt);
            }
        });

        tfSprak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSprakKeyTyped(evt);
            }
        });

        tfValuta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfValutaKeyTyped(evt);
            }
        });

        tfTidszon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTidszonKeyTyped(evt);
            }
        });

        tfEkonomi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfEkonomiKeyTyped(evt);
            }
        });

        tfPolitiskStruktur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPolitiskStrukturKeyTyped(evt);
            }
        });

        lblFelMSprak.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMSprak.setText("Kan inte vara tomt!");

        lblFelMNamn.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMNamn.setText("Kan inte vara tomt!");

        lblFelMValuta.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMValuta.setText("Kan inte vara tomt!");

        lblFelMTidszon.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMTidszon.setText("Kan inte vara tomt!");

        lblFelMPolitiskStruktur.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMPolitiskStruktur.setText("Kan inte vara tomt!");

        lblFelMEkonomi.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMEkonomi.setText("Kan inte vara tomt!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTillbaka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSpara)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEkonomi)
                            .addComponent(lblValuta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTidszon)
                            .addComponent(lblPolitiskStruktur)
                            .addComponent(lblSprak)
                            .addComponent(lblNamn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTidszon)
                            .addComponent(tfEkonomi)
                            .addComponent(tfPolitiskStruktur)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfSprak)
                            .addComponent(tfValuta))))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFelMPolitiskStruktur)
                    .addComponent(lblFelMNamn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblFelMSprak)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFelMEkonomi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFelMTidszon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFelMValuta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamn)
                    .addComponent(lblFelMNamn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSprak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSprak)
                    .addComponent(lblFelMSprak))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValuta)
                    .addComponent(tfValuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelMValuta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTidszon)
                    .addComponent(lblFelMTidszon)
                    .addComponent(tfTidszon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPolitiskStruktur)
                    .addComponent(tfPolitiskStruktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelMPolitiskStruktur))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEkonomi)
                    .addComponent(lblFelMEkonomi)
                    .addComponent(tfEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnSpara))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        if(harOsparadeAndringar()){
            new OsparadeAndringarFonster(idb, inloggadAnvandare, "Land").setVisible(true);
        }
        else{
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        doljFelMeddelanden();
        
        boolean formatKorrekt = true;
        
        String namn = tfNamn.getText();
        if(!namn.isEmpty()){
            aktuelltLand.setNamn(namn);
        }
        else{
            formatKorrekt = false;
            lblFelMNamn.setVisible(true);
        }
        
        String sprak = tfSprak.getText();
        if(!sprak.isEmpty()){
            aktuelltLand.setSprak(sprak);
        }
        else{
            formatKorrekt = false;
            lblFelMSprak.setVisible(true);
        }
        
        String valuta = tfValuta.getText();
        if(!valuta.isEmpty()){
            aktuelltLand.setValuta(valuta);
        }
        else{
            formatKorrekt = false;
            lblFelMValuta.setVisible(true);
        }
        
        String tidszon = tfTidszon.getText();
        if(!tidszon.isEmpty()){
            aktuelltLand.setTidszon(tidszon);
        }
        else{
            formatKorrekt = false;
            lblFelMTidszon.setVisible(true);
        }
        
        String politiskStruktur = tfPolitiskStruktur.getText();
        if(!politiskStruktur.isEmpty()){
            aktuelltLand.setPolitiskStruktur(politiskStruktur);
        }
        else{
            formatKorrekt = false;
            lblFelMPolitiskStruktur.setVisible(true);
        }
        
        String ekonomi = tfEkonomi.getText();
        if(!ekonomi.isEmpty()){
            aktuelltLand.setEkonomi(ekonomi);
        }
        else{
            formatKorrekt = false;
            lblFelMEkonomi.setVisible(true);
        }
        
        if(formatKorrekt){
            aktuelltLand.updateLandDB();
            forraFonstret.uppdateraFonster();
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnSparaActionPerformed

    private void tfNamnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNamnKeyTyped
        btnSpara.setEnabled(true);
    }//GEN-LAST:event_tfNamnKeyTyped

    private void tfSprakKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSprakKeyTyped
        btnSpara.setEnabled(true);
    }//GEN-LAST:event_tfSprakKeyTyped

    private void tfValutaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValutaKeyTyped
        btnSpara.setEnabled(true);
    }//GEN-LAST:event_tfValutaKeyTyped

    private void tfTidszonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTidszonKeyTyped
        btnSpara.setEnabled(true);
    }//GEN-LAST:event_tfTidszonKeyTyped

    private void tfPolitiskStrukturKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPolitiskStrukturKeyTyped
        btnSpara.setEnabled(true);
    }//GEN-LAST:event_tfPolitiskStrukturKeyTyped

    private void tfEkonomiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEkonomiKeyTyped
        btnSpara.setEnabled(true);
    }//GEN-LAST:event_tfEkonomiKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedigeraLandFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedigeraLandFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedigeraLandFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedigeraLandFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LandInfoFonster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel lblEkonomi;
    private javax.swing.JLabel lblFelMEkonomi;
    private javax.swing.JLabel lblFelMNamn;
    private javax.swing.JLabel lblFelMPolitiskStruktur;
    private javax.swing.JLabel lblFelMSprak;
    private javax.swing.JLabel lblFelMTidszon;
    private javax.swing.JLabel lblFelMValuta;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblPolitiskStruktur;
    private javax.swing.JLabel lblSprak;
    private javax.swing.JLabel lblTidszon;
    private javax.swing.JLabel lblValuta;
    private javax.swing.JTextField tfEkonomi;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfPolitiskStruktur;
    private javax.swing.JTextField tfSprak;
    private javax.swing.JTextField tfTidszon;
    private javax.swing.JTextField tfValuta;
    // End of variables declaration//GEN-END:variables
}
