/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024.fonster;



import ngo2024.*;
import oru.inf.InfDB;
import java.util.*;
import oru.inf.InfException;
import java.time.*;
import java.sql.Date;
import ngo2024.AnvandarRegister;
import javax.swing.ImageIcon;
/**
 *
 * @author Gastinlogg
 */
public class RegistreraAnstalldFonster extends javax.swing.JFrame {

    private InfDB idb;
    private Anvandare inloggadAnvandare;
    private Anvandare anvandareRegistrera;
    private HanteraAnstalldaFonster forraFonstret;
    private AnvandarRegister anstallda;
    
    /**
     * Creates new form LaggTillTaBortFonster
     */
    public RegistreraAnstalldFonster(InfDB idb, Anvandare inloggadAnvandare, HanteraAnstalldaFonster forraFonstret) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        anstallda = new AnvandarRegister(idb);
        anvandareRegistrera = null;
        initComponents();
        setLocationRelativeTo(null);
        doljFelmeddelanden();
        lblAnsvarighetsomrade.setVisible(false);
        tfAnsvarighetsomrade.setVisible(false);
        lblMentor.setVisible(false);
        tfMentorsID.setVisible(false);
        lblHanvisningMentor.setVisible(false);
        this.forraFonstret = forraFonstret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblFornamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblTelefonNr = new javax.swing.JLabel();
        lblAvdelning = new javax.swing.JLabel();
        cbAvdelning = new javax.swing.JComboBox<>();
        tfFornamn = new javax.swing.JTextField();
        tfEfternamn = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfEpost = new javax.swing.JTextField();
        tfTelefonNr = new javax.swing.JTextField();
        lblFelMFornamn = new javax.swing.JLabel();
        lblFelMEfternamn = new javax.swing.JLabel();
        lblFelMAdress = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        btnSlumpaLosenord = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblLosenordSlumpas = new javax.swing.JLabel();
        lblFelMEpost = new javax.swing.JLabel();
        lblFelMTelefon = new javax.swing.JLabel();
        btnRegistrera = new javax.swing.JButton();
        lblFelMAvdelning = new javax.swing.JLabel();
        cbRoll = new javax.swing.JComboBox<>();
        lblRoll = new javax.swing.JLabel();
        lblFelMRoll = new javax.swing.JLabel();
        lblAnsvarighetsomrade = new javax.swing.JLabel();
        lblMentor = new javax.swing.JLabel();
        tfAnsvarighetsomrade = new javax.swing.JTextField();
        tfMentorsID = new javax.swing.JTextField();
        lblHanvisningMentor = new javax.swing.JLabel();
        lblFelMAnsvar = new javax.swing.JLabel();
        lblFelMTommaFalt = new javax.swing.JLabel();

        setTitle("Registrera");
        setIconImage(new ImageIcon(getClass().getResource("/resources/icons/appLogo.png")).getImage());
        setResizable(false);

        lblRubrik.setText("Registrera ny anställd");

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblFornamn.setText("Förnamn:");

        lblEfternamn.setText("Efternamn:");

        lblAdress.setText("Adress:");

        lblEpost.setText("Epost:");

        lblTelefonNr.setText("Telefon:");

        lblAvdelning.setText("Avdelning:");

        cbAvdelning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj avdelning...", "Hållbar Energi och Klimatförändringar", "Samhällsutveckling och Utbildning", "Teknologisk Innovation och Entrepenörskap" }));
        cbAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAvdelningActionPerformed(evt);
            }
        });

        tfFornamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFornamnActionPerformed(evt);
            }
        });

        tfEfternamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEfternamnActionPerformed(evt);
            }
        });

        tfAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAdressActionPerformed(evt);
            }
        });

        lblFelMFornamn.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMFornamn.setText("Kan endast innehålla bokstäver!");

        lblFelMEfternamn.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMEfternamn.setText("Kan endast innehålla bokstäver!");

        lblFelMAdress.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMAdress.setText("Adressen måste anges i formatet \"Nummer Gatuadress, Platsnamn\"!");

        lblLosenord.setText("Lösenord:");

        btnSlumpaLosenord.setText("Slumpa lösenord");
        btnSlumpaLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlumpaLosenordActionPerformed(evt);
            }
        });

        lblLosenordSlumpas.setText(" ");

        lblFelMEpost.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMEpost.setText("Epost bör följa format: exempel@domän.com");

        lblFelMTelefon.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMTelefon.setText("Telefonnummer kan endast innehålla siffror, bindestreck och det kan börja med +!");

        btnRegistrera.setText("Registrera");
        btnRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraActionPerformed(evt);
            }
        });

        lblFelMAvdelning.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMAvdelning.setText("Välj en avdelning!");

        cbRoll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj roll...", "Handläggare", "Administratör" }));
        cbRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRollActionPerformed(evt);
            }
        });

        lblRoll.setText("Roll:");

        lblFelMRoll.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMRoll.setText("Välj en roll!");

        lblAnsvarighetsomrade.setText("Ansvarighetsområde:");

        lblMentor.setText("Mentor:");

        tfAnsvarighetsomrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnsvarighetsomradeActionPerformed(evt);
            }
        });

        tfMentorsID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMentorsIDActionPerformed(evt);
            }
        });

        lblHanvisningMentor.setForeground(new java.awt.Color(255, 0, 51));
        lblHanvisningMentor.setText("Ange AnställningsID på mentorn alternativt lämna tom om mentor saknas!");

        lblFelMAnsvar.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMAnsvar.setText("Ange ansvarighetsområde!");

        lblFelMTommaFalt.setForeground(new java.awt.Color(255, 0, 51));
        lblFelMTommaFalt.setText("Inget av fälten får vara tomt!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblRubrik))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFornamn)
                            .addComponent(jButton1)
                            .addComponent(lblEfternamn)
                            .addComponent(lblAvdelning)
                            .addComponent(lblAdress)
                            .addComponent(lblEpost)
                            .addComponent(lblTelefonNr)
                            .addComponent(lblLosenord)
                            .addComponent(lblRoll)
                            .addComponent(lblAnsvarighetsomrade)
                            .addComponent(lblMentor))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfFornamn, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                            .addComponent(tfAdress, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfEfternamn, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblFelMFornamn)
                                                    .addComponent(lblFelMEfternamn))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(lblFelMAdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cbAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11)
                                                    .addComponent(lblLosenordSlumpas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblFelMAvdelning)
                                                    .addComponent(btnSlumpaLosenord)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(tfTelefonNr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                                    .addComponent(tfEpost, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblFelMEpost)
                                                    .addComponent(lblFelMTelefon)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfMentorsID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblHanvisningMentor))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblFelMRoll))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfAnsvarighetsomrade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblFelMAnsvar)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnRegistrera)
                                .addGap(18, 18, 18)
                                .addComponent(lblFelMTommaFalt)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblRubrik)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornamn)
                    .addComponent(tfFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelMFornamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEfternamn)
                    .addComponent(tfEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelMEfternamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdress)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFelMAdress)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelMEpost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonNr)
                    .addComponent(tfTelefonNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelMTelefon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdelning)
                    .addComponent(cbAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelMAvdelning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(btnSlumpaLosenord)
                    .addComponent(jLabel11)
                    .addComponent(lblLosenordSlumpas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoll)
                    .addComponent(cbRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelMRoll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnsvarighetsomrade)
                    .addComponent(tfAnsvarighetsomrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelMAnsvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMentor)
                    .addComponent(tfMentorsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHanvisningMentor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnRegistrera)
                    .addComponent(lblFelMTommaFalt))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doljFelmeddelanden(){
        lblFelMFornamn.setVisible(false);
        lblFelMEfternamn.setVisible(false);
        lblFelMAdress.setVisible(false);
        lblFelMEpost.setVisible(false);
        lblFelMTelefon.setVisible(false);
        lblFelMAvdelning.setVisible(false);
        lblFelMRoll.setVisible(false);
        lblFelMAnsvar.setVisible(false);
        lblFelMTommaFalt.setVisible(false);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAvdelningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAvdelningActionPerformed

    private void tfFornamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFornamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFornamnActionPerformed

    private void tfEfternamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEfternamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEfternamnActionPerformed

    private void tfAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAdressActionPerformed

    private void btnSlumpaLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlumpaLosenordActionPerformed
        
        //skapar en strängvariabel som innehåller alla siffror
        String siffror = "0123456789";
        //likaså med bokstäver
        String bokstaver = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
        //sätter ihop siffror och bokstäver till en sträng
        String allaTecken = siffror + bokstaver;
        
        //skapar ett objekt av klassen Random för att kunna generera ett slumpmässigt lösenord
        Random slumpa = new Random();
        
        //skapar ett objekt av klassen StringBuilder. Denna används för att kunna skapa och manipulera fram en sträng.
        //Vi skapar en nytt objekt av StringBuilder som döps till losenord vilket för närvarande är en tom sträng
        StringBuilder losenord = new StringBuilder();
        //denna fylls på i kodraderna nedan

        // Slumpar fram en siffra och lägger till en siffra först i variabeln losenord för att säkerställa att det blir minst en i strängen
        //nextint är en metod i klassen Random. Returnerar ett slumpmässigt tal mellan 0 och längden på variabeln siffror(10).
        //denna returnerar indexpositionen för siffran, dvs 0-9.
        //charAt hämtar tecknet som ligger på den indexpositionen som returnerats av nextInt metoden.
        //append är en metod i StringBuilder som lägger till tecknet i "losenord".
        losenord.append(siffror.charAt(slumpa.nextInt(siffror.length())));

        // Lägger till resten av tecknen så att lösenordet blir 8 tecken långt
        //startar från index 1 med anledning av att en siffra redan lagts till
        for (int i = 1; i < 8; i++) {
            losenord.append(allaTecken.charAt(slumpa.nextInt(allaTecken.length())));
        }
        //sätter labeln till nya lösenordet som slumpats fram och konverterar från StringBuilder till en vanlig String.
        lblLosenordSlumpas.setText(losenord.toString());
    }//GEN-LAST:event_btnSlumpaLosenordActionPerformed

    private void btnRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraActionPerformed
        
        boolean faltIfyllda = true;
        boolean formatKorrekt = true;
        doljFelmeddelanden();
        
        String fornamn = tfFornamn.getText();
        String efternamn = tfEfternamn.getText();
        String adress = tfAdress.getText();
        String epost = tfEpost.getText();
        String telefonNr = tfTelefonNr.getText();
        String angettID = tfMentorsID.getText();
        String mentor = null;
        
        if(fornamn.isEmpty() || efternamn.isEmpty() || adress.isEmpty() || epost.isEmpty() || telefonNr.isEmpty() || lblLosenordSlumpas.getText().isEmpty()){
            faltIfyllda = false;
            formatKorrekt = false;
            lblFelMTommaFalt.setVisible(true);
        }
        
        if(faltIfyllda){
            if(!Validerare.formatEnkeltNamnOK(fornamn)){
                formatKorrekt = false;
                lblFelMFornamn.setVisible(true);
            }
            if(!Validerare.formatEnkeltNamnOK(efternamn)){
                formatKorrekt = false;
                lblFelMEfternamn.setVisible(true);
            }
            if(!Validerare.arAdress(adress)){
                formatKorrekt = false;
                lblFelMAdress.setVisible(true);   
            }
            if(!Validerare.arEpostAdress(epost)){
                formatKorrekt = false;
                lblFelMEpost.setVisible(true);  
            }
            if(!Validerare.arTelefonnummer(telefonNr)){
                formatKorrekt = false;
                lblFelMTelefon.setVisible(true);  
            }
            if(cbAvdelning.getSelectedItem().equals("Välj avdelning...")){
                formatKorrekt = false;
                lblFelMAvdelning.setVisible(true);
            }
            if(cbRoll.getSelectedItem().equals("Välj roll...")){
                formatKorrekt = false;
                lblFelMRoll.setVisible(true);
            }
        
            if(cbRoll.getSelectedItem().equals("Handläggare")){
            
                if(tfAnsvarighetsomrade.getText().isEmpty()){
                    formatKorrekt = false;
                    lblFelMAnsvar.setVisible(true);
                }
            
                if(!tfMentorsID.getText().isEmpty()){
                    if(!Validerare.arSiffror(angettID)){
                    formatKorrekt = false;
                    lblHanvisningMentor.setText("Anges med siffror!");
                    }
                    else {
                    mentor = tfMentorsID.getText();
                    }
                }
                if(mentor != null) {
                    System.out.println(mentor);
                    System.out.println(anstallda.hamtaHandlaggare());
                    if(!anstallda.hamtaHandlaggare().contains(mentor)){
                        formatKorrekt = false;
                        lblHanvisningMentor.setText("Finns ej handläggare med angett ID!");
                    }      
                }
            }
        }
        
   if(formatKorrekt){
        
        int aid = anstallda.getMaxAID() + 1;
        String aidString = Integer.toString(aid);
        anvandareRegistrera = new Anvandare(idb, aidString);
        
        //hämtar dagens datum
        LocalDate dagensDatum = LocalDate.now();
        Date anstallningsdatum = Date.valueOf(dagensDatum);
        
        //hämtar lösenordet som slumpats fram för att kunna använda i sql frågan
        String losenord = lblLosenord.getText();
        
        //omvandlar val av avd. till siffra 
        int avdelning;
        if(cbAvdelning.getSelectedItem().equals("Hållbar Energi och Klimatförändringar")){
            avdelning = 1;
            }
        else if(cbAvdelning.getSelectedItem().equals("Samhällsutveckling och Utbildning")){
            avdelning = 2;
            }
            else{
            avdelning = 3;
            }
            
        anvandareRegistrera.laggTillAnvandareDb(aid, fornamn, efternamn, adress, epost, telefonNr, anstallningsdatum, losenord, avdelning);
        
        //hämtar data för att kunna lägga till i handläggartabellen
        if(cbRoll.getSelectedItem().equals("Handläggare")){
            String beskrivningAnsvar = tfAnsvarighetsomrade.getText();
         
            if(mentor != null){
                anvandareRegistrera.laggTillHandlaggareMedMentorDb(aid, beskrivningAnsvar, mentor);
            }else {
                anvandareRegistrera.laggTillHandlaggareUtanMentorDb(aid, beskrivningAnsvar);
            }
        }   
        //hämtar data för att kunna lägga till i anställd tabellen, kan ta bort villkoret
        else if(cbRoll.getSelectedItem().equals("Administatör")){
            anvandareRegistrera.laggTillAdminDb(aid);
            }
       
        this.setVisible(false);
        forraFonstret.visaAnstallda();
    }     
       
    }//GEN-LAST:event_btnRegistreraActionPerformed

    private void cbRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRollActionPerformed
        if(cbRoll.getSelectedItem().equals("Handläggare")){
            lblAnsvarighetsomrade.setVisible(true);
            tfAnsvarighetsomrade.setVisible(true);
            lblMentor.setVisible(true);
            tfMentorsID.setVisible(true);
            lblHanvisningMentor.setVisible(true);
        }
        else {
            lblAnsvarighetsomrade.setVisible(false);
            tfAnsvarighetsomrade.setVisible(false);
            lblMentor.setVisible(false);
            tfMentorsID.setVisible(false);
            lblHanvisningMentor.setVisible(false);
        }
    }//GEN-LAST:event_cbRollActionPerformed

    private void tfAnsvarighetsomradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnsvarighetsomradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnsvarighetsomradeActionPerformed

    private void tfMentorsIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMentorsIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMentorsIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistreraAnstalldFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistreraAnstalldFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistreraAnstalldFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistreraAnstalldFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LaggTillTaBortAnstalldFonster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrera;
    private javax.swing.JButton btnSlumpaLosenord;
    private javax.swing.JComboBox<String> cbAvdelning;
    private javax.swing.JComboBox<String> cbRoll;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAnsvarighetsomrade;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFelMAdress;
    private javax.swing.JLabel lblFelMAnsvar;
    private javax.swing.JLabel lblFelMAvdelning;
    private javax.swing.JLabel lblFelMEfternamn;
    private javax.swing.JLabel lblFelMEpost;
    private javax.swing.JLabel lblFelMFornamn;
    private javax.swing.JLabel lblFelMRoll;
    private javax.swing.JLabel lblFelMTelefon;
    private javax.swing.JLabel lblFelMTommaFalt;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblHanvisningMentor;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblLosenordSlumpas;
    private javax.swing.JLabel lblMentor;
    private javax.swing.JLabel lblRoll;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblTelefonNr;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfAnsvarighetsomrade;
    private javax.swing.JTextField tfEfternamn;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfFornamn;
    private javax.swing.JTextField tfMentorsID;
    private javax.swing.JTextField tfTelefonNr;
    // End of variables declaration//GEN-END:variables
}
